/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import DataLayer.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Black Tony
 */
public class CourseWindow extends javax.swing.JFrame {

    View parentView = null;
    String courseId = null;
    String option;
    
    
    /**
     * Creates new form CourseWindow with ability to get back to 
     */
    public CourseWindow(View v, String option) {
        initComponents();
        this.option = option;
        parentView = v;
        setCourseWindow();
    }
    
    // This is the constructor for doing edits on a Course
    public CourseWindow(View v, String courseId, String option){
        initComponents();
        parentView = v;
        this.courseId = courseId;
        this.option = option;
        setCourseWindow();
    }
    
    public void setCourseWindow(){
        Users faculty = new Users();
        ArrayList<User> facultyArrayList = faculty.getUsers();
        String[] userNames = new String[facultyArrayList.size()];
        for (int i = 0; i<= facultyArrayList.size() -1; i++){
            System.out.println(facultyArrayList.get(i).getLName());
            userNames[i] = facultyArrayList.get(i).getLName();
        }
        facultyList.setListData(userNames);
        //lModel.addElement(facultyArrayList.get(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearField = new javax.swing.JTextField();
        courseNumberField = new javax.swing.JTextField();
        courseNameField = new javax.swing.JTextField();
        facultyPane = new javax.swing.JScrollPane();
        facultyList = new javax.swing.JList(new DefaultListModel<String>());
        submitCourse = new javax.swing.JButton();
        cancelUser = new javax.swing.JButton();
        yearLabel = new javax.swing.JLabel();
        courseNumberLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        facultyMemberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        yearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFieldActionPerformed(evt);
            }
        });

        courseNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNumberFieldActionPerformed(evt);
            }
        });

        facultyPane.setViewportView(facultyList);

        submitCourse.setText("Submit");
        submitCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitCourseMouseClicked(evt);
            }
        });

        cancelUser.setText("Cancel");
        cancelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelUserMouseClicked(evt);
            }
        });

        yearLabel.setText("Year");

        courseNumberLabel.setText("Course Number");

        courseNameLabel.setText("Course Name");

        facultyMemberLabel.setText("Faculty Member");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facultyMemberLabel)
                        .addGap(35, 35, 35)
                        .addComponent(yearLabel)
                        .addGap(56, 56, 56)
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facultyPane, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNumberLabel)
                            .addComponent(courseNameLabel)
                            .addComponent(cancelUser))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(submitCourse))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyMemberLabel)
                            .addComponent(yearLabel))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(courseNumberLabel)
                        .addGap(17, 17, 17)
                        .addComponent(courseNameLabel)
                        .addGap(59, 59, 59)
                        .addComponent(cancelUser))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(submitCourse))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFieldActionPerformed

    private void courseNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNumberFieldActionPerformed

    private void submitCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitCourseMouseClicked
        //To Do
        //Do database insertions
        //If successful, update parent view's table
        if(courseNameField.getText() != null && courseNumberField.getText() != null && yearField.getText() != null && !facultyList.isSelectionEmpty()){
            if("Update".equals(option)){
                try {
                    User selectedUser =(User) facultyList.getSelectedValue();
                    Course updateCourse = new Course(selectedUser.getUserId(), courseId, yearField.getText(), courseNumberField.getText(), courseNameField.getText());
                    updateCourse.post();
                    this.setVisible(false);
                    parentView.setEnabled(true);
                } catch (DLException ex) {
                    //Create Error dialog
                }
            }
        }
        
        //If not, pop a message out
    }//GEN-LAST:event_submitCourseMouseClicked

    private void cancelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelUserMouseClicked
        //The user wanted to cancel out of the operation?  Easy.
        this.setVisible(false);
        parentView.setEnabled(true);
    }//GEN-LAST:event_cancelUserMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelUser;
    private javax.swing.JTextField courseNameField;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNumberField;
    private javax.swing.JLabel courseNumberLabel;
    private javax.swing.JList facultyList;
    private javax.swing.JLabel facultyMemberLabel;
    private javax.swing.JScrollPane facultyPane;
    private javax.swing.JButton submitCourse;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
