package PresentationLayer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Black Tony
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPane = new javax.swing.JTabbedPane();
        welcomePanel = new javax.swing.JPanel();
        logoutButton = new java.awt.Button();
        loginPane = new javax.swing.JScrollPane();
        loginText = new javax.swing.JTextArea();
        teachingPanel = new javax.swing.JPanel();
        teachingPane = new javax.swing.JScrollPane();
        teachingTable = new javax.swing.JTable();
        newTeaching = new javax.swing.JButton();
        editTeaching = new javax.swing.JButton();
        servicesPanel = new javax.swing.JPanel();
        newService = new javax.swing.JButton();
        editService = new javax.swing.JButton();
        servicesPane = new javax.swing.JScrollPane();
        servicesTable = new javax.swing.JTable();
        scholarshipPanel = new javax.swing.JPanel();
        newScholarship = new javax.swing.JButton();
        editScholarship = new javax.swing.JButton();
        scholarshipPane = new javax.swing.JScrollPane();
        scholarshipTable = new javax.swing.JTable();
        publicationsPanel = new javax.swing.JPanel();
        newPublication = new javax.swing.JButton();
        updatePublication = new javax.swing.JButton();
        publicationsPane = new javax.swing.JScrollPane();
        publicationsTable = new javax.swing.JTable();
        kudosPanel = new javax.swing.JPanel();
        newKudo = new javax.swing.JButton();
        updateKudo = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        usersPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Educational Editor");

        logoutButton.setActionCommand("logoutButton");
        logoutButton.setLabel("Logout");
        logoutButton.setName("logoutButton"); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        loginText.setEditable(false);
        loginText.setColumns(20);
        loginText.setLineWrap(true);
        loginText.setRows(5);
        loginText.setText("Thank you for logging in.  Above are tabs that will allow you to view and in some cases edit data.  When you are done you may logout by clicking the button below.");
        loginText.setWrapStyleWord(true);
        loginPane.setViewportView(loginText);

        org.jdesktop.layout.GroupLayout welcomePanelLayout = new org.jdesktop.layout.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomePanelLayout.createSequentialGroup()
                .add(348, 348, 348)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(loginPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomePanelLayout.createSequentialGroup()
                .add(69, 69, 69)
                .add(loginPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutButton.getAccessibleContext().setAccessibleName("logoutButton");

        viewPane.addTab("Welcome", welcomePanel);

        teachingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Course Number", "Course Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        teachingTable.getTableHeader().setReorderingAllowed(false);
        teachingPane.setViewportView(teachingTable);
        teachingTable.getColumnModel().getColumn(0).setResizable(false);
        teachingTable.getColumnModel().getColumn(1).setResizable(false);
        teachingTable.getColumnModel().getColumn(2).setResizable(false);
        teachingTable.getColumnModel().getColumn(3).setResizable(false);

        newTeaching.setText("Create New");
        newTeaching.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newTeachingMouseClicked(evt);
            }
        });

        editTeaching.setText("Update Selected");

        org.jdesktop.layout.GroupLayout teachingPanelLayout = new org.jdesktop.layout.GroupLayout(teachingPanel);
        teachingPanel.setLayout(teachingPanelLayout);
        teachingPanelLayout.setHorizontalGroup(
            teachingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teachingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(teachingPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, teachingPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editTeaching)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newTeaching)
                .addContainerGap())
        );
        teachingPanelLayout.setVerticalGroup(
            teachingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, teachingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(teachingPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(teachingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newTeaching)
                    .add(editTeaching))
                .addContainerGap())
        );

        viewPane.addTab("Teaching", teachingPanel);

        newService.setText("Create New");

        editService.setText("Update Selected");

        servicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Description", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        servicesTable.getTableHeader().setReorderingAllowed(false);
        servicesPane.setViewportView(servicesTable);
        servicesTable.getColumnModel().getColumn(0).setResizable(false);
        servicesTable.getColumnModel().getColumn(1).setResizable(false);
        servicesTable.getColumnModel().getColumn(2).setResizable(false);
        servicesTable.getColumnModel().getColumn(3).setResizable(false);

        org.jdesktop.layout.GroupLayout servicesPanelLayout = new org.jdesktop.layout.GroupLayout(servicesPanel);
        servicesPanel.setLayout(servicesPanelLayout);
        servicesPanelLayout.setHorizontalGroup(
            servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(servicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(servicesPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, servicesPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editService)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newService)
                .addContainerGap())
        );
        servicesPanelLayout.setVerticalGroup(
            servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, servicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(servicesPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newService)
                    .add(editService))
                .addContainerGap())
        );

        viewPane.addTab("Services", servicesPanel);

        newScholarship.setText("Create New");

        editScholarship.setText("Update Selected");

        scholarshipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Citation", "Tease", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scholarshipTable.getTableHeader().setReorderingAllowed(false);
        scholarshipPane.setViewportView(scholarshipTable);
        scholarshipTable.getColumnModel().getColumn(0).setResizable(false);
        scholarshipTable.getColumnModel().getColumn(1).setResizable(false);
        scholarshipTable.getColumnModel().getColumn(2).setResizable(false);
        scholarshipTable.getColumnModel().getColumn(3).setResizable(false);
        scholarshipTable.getColumnModel().getColumn(5).setResizable(false);

        org.jdesktop.layout.GroupLayout scholarshipPanelLayout = new org.jdesktop.layout.GroupLayout(scholarshipPanel);
        scholarshipPanel.setLayout(scholarshipPanelLayout);
        scholarshipPanelLayout.setHorizontalGroup(
            scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scholarshipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scholarshipPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scholarshipPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editScholarship)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newScholarship)
                .addContainerGap())
        );
        scholarshipPanelLayout.setVerticalGroup(
            scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scholarshipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scholarshipPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newScholarship)
                    .add(editScholarship))
                .addContainerGap())
        );

        viewPane.addTab("Scholarship", scholarshipPanel);

        newPublication.setText("Create New");

        updatePublication.setText("Update Selected");

        publicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Course Number", "Course Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        publicationsTable.getTableHeader().setReorderingAllowed(false);
        publicationsPane.setViewportView(publicationsTable);
        publicationsTable.getColumnModel().getColumn(0).setResizable(false);
        publicationsTable.getColumnModel().getColumn(1).setResizable(false);
        publicationsTable.getColumnModel().getColumn(2).setResizable(false);
        publicationsTable.getColumnModel().getColumn(3).setResizable(false);
        publicationsTable.getColumnModel().getColumn(4).setResizable(false);

        org.jdesktop.layout.GroupLayout publicationsPanelLayout = new org.jdesktop.layout.GroupLayout(publicationsPanel);
        publicationsPanel.setLayout(publicationsPanelLayout);
        publicationsPanelLayout.setHorizontalGroup(
            publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(publicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(publicationsPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, publicationsPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(updatePublication)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newPublication)
                .addContainerGap())
        );
        publicationsPanelLayout.setVerticalGroup(
            publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, publicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(publicationsPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newPublication)
                    .add(updatePublication))
                .addContainerGap())
        );

        viewPane.addTab("Publications", publicationsPanel);

        newKudo.setText("Create New");

        updateKudo.setText("Update Selected");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Kudo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTable6);
        jTable6.getColumnModel().getColumn(0).setResizable(false);
        jTable6.getColumnModel().getColumn(1).setResizable(false);
        jTable6.getColumnModel().getColumn(2).setResizable(false);

        org.jdesktop.layout.GroupLayout kudosPanelLayout = new org.jdesktop.layout.GroupLayout(kudosPanel);
        kudosPanel.setLayout(kudosPanelLayout);
        kudosPanelLayout.setHorizontalGroup(
            kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(kudosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kudosPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(updateKudo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newKudo)
                .addContainerGap())
        );
        kudosPanelLayout.setVerticalGroup(
            kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kudosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newKudo)
                    .add(updateKudo))
                .addContainerGap())
        );

        viewPane.addTab("Kudos", kudosPanel);

        usersPanel.setEnabled(false);

        jButton3.setText("Create New");

        jButton4.setText("Update Selected");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "E-Mail", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setResizable(false);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setResizable(false);

        org.jdesktop.layout.GroupLayout usersPanelLayout = new org.jdesktop.layout.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, usersPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton3)
                .addContainerGap())
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton4))
                .addContainerGap())
        );

        viewPane.addTab("Users", usersPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewPane)
        );

        viewPane.getAccessibleContext().setAccessibleName("User");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("test");
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newTeachingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTeachingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newTeachingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editScholarship;
    private javax.swing.JButton editService;
    private javax.swing.JButton editTeaching;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable6;
    private javax.swing.JPanel kudosPanel;
    private javax.swing.JScrollPane loginPane;
    private javax.swing.JTextArea loginText;
    private java.awt.Button logoutButton;
    private javax.swing.JButton newKudo;
    private javax.swing.JButton newPublication;
    private javax.swing.JButton newScholarship;
    private javax.swing.JButton newService;
    private javax.swing.JButton newTeaching;
    private javax.swing.JScrollPane publicationsPane;
    private javax.swing.JPanel publicationsPanel;
    private javax.swing.JTable publicationsTable;
    private javax.swing.JScrollPane scholarshipPane;
    private javax.swing.JPanel scholarshipPanel;
    private javax.swing.JTable scholarshipTable;
    private javax.swing.JScrollPane servicesPane;
    private javax.swing.JPanel servicesPanel;
    private javax.swing.JTable servicesTable;
    private javax.swing.JScrollPane teachingPane;
    private javax.swing.JPanel teachingPanel;
    private javax.swing.JTable teachingTable;
    private javax.swing.JButton updateKudo;
    private javax.swing.JButton updatePublication;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTabbedPane viewPane;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
