package PresentationLayer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Black Tony
 */
public class View extends javax.swing.JFrame {

    private javax.swing.JFrame n;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPane = new javax.swing.JTabbedPane();
        welcomePanel = new javax.swing.JPanel();
        logoutButton = new java.awt.Button();
        loginPane = new javax.swing.JScrollPane();
        loginText = new javax.swing.JTextArea();
        CoursesPanel = new javax.swing.JPanel();
        coursesPane = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        newCourse = new javax.swing.JButton();
        editCourses = new javax.swing.JButton();
        servicesPanel = new javax.swing.JPanel();
        newService = new javax.swing.JButton();
        editService = new javax.swing.JButton();
        servicesPane = new javax.swing.JScrollPane();
        servicesTable = new javax.swing.JTable();
        scholarshipPanel = new javax.swing.JPanel();
        newScholarship = new javax.swing.JButton();
        editScholarship = new javax.swing.JButton();
        scholarshipsPane = new javax.swing.JScrollPane();
        scholarshipsTable = new javax.swing.JTable();
        publicationsPanel = new javax.swing.JPanel();
        newPublication = new javax.swing.JButton();
        updatePublication = new javax.swing.JButton();
        publicationsPane = new javax.swing.JScrollPane();
        publicationsTable = new javax.swing.JTable();
        kudosPanel = new javax.swing.JPanel();
        newKudo = new javax.swing.JButton();
        updateKudo = new javax.swing.JButton();
        kudosPane = new javax.swing.JScrollPane();
        kudosTable = new javax.swing.JTable();
        usersPanel = new javax.swing.JPanel();
        newUser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        usersPane = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Educational Editor");

        logoutButton.setActionCommand("logoutButton");
        logoutButton.setLabel("Logout");
        logoutButton.setName("logoutButton"); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        loginText.setEditable(false);
        loginText.setColumns(20);
        loginText.setLineWrap(true);
        loginText.setRows(5);
        loginText.setText("Thank you for logging in.  Above are tabs that will allow you to view and in some cases edit data.  When you are done you may logout by clicking the button below.");
        loginText.setWrapStyleWord(true);
        loginPane.setViewportView(loginText);

        org.jdesktop.layout.GroupLayout welcomePanelLayout = new org.jdesktop.layout.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomePanelLayout.createSequentialGroup()
                .add(348, 348, 348)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(loginPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomePanelLayout.createSequentialGroup()
                .add(69, 69, 69)
                .add(loginPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutButton.getAccessibleContext().setAccessibleName("logoutButton");

        viewPane.addTab("Welcome", welcomePanel);

        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Course Number", "Course Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        coursesTable.getTableHeader().setReorderingAllowed(false);
        coursesPane.setViewportView(coursesTable);
        coursesTable.getColumnModel().getColumn(0).setResizable(false);
        coursesTable.getColumnModel().getColumn(1).setResizable(false);
        coursesTable.getColumnModel().getColumn(2).setResizable(false);
        coursesTable.getColumnModel().getColumn(3).setResizable(false);

        newCourse.setText("Create New");
        newCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCourseMouseClicked(evt);
            }
        });

        editCourses.setText("Update Selected");
        editCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCoursesMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout CoursesPanelLayout = new org.jdesktop.layout.GroupLayout(CoursesPanel);
        CoursesPanel.setLayout(CoursesPanelLayout);
        CoursesPanelLayout.setHorizontalGroup(
            CoursesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(coursesPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, CoursesPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editCourses)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newCourse)
                .addContainerGap())
        );
        CoursesPanelLayout.setVerticalGroup(
            CoursesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, CoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(coursesPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(CoursesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newCourse)
                    .add(editCourses))
                .addContainerGap())
        );

        viewPane.addTab("Courses", CoursesPanel);

        newService.setText("Create New");
        newService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newServiceMouseClicked(evt);
            }
        });

        editService.setText("Update Selected");
        editService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editServiceMouseClicked(evt);
            }
        });

        servicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Description", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        servicesTable.getTableHeader().setReorderingAllowed(false);
        servicesPane.setViewportView(servicesTable);
        servicesTable.getColumnModel().getColumn(0).setResizable(false);
        servicesTable.getColumnModel().getColumn(1).setResizable(false);
        servicesTable.getColumnModel().getColumn(2).setResizable(false);
        servicesTable.getColumnModel().getColumn(3).setResizable(false);

        org.jdesktop.layout.GroupLayout servicesPanelLayout = new org.jdesktop.layout.GroupLayout(servicesPanel);
        servicesPanel.setLayout(servicesPanelLayout);
        servicesPanelLayout.setHorizontalGroup(
            servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(servicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(servicesPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, servicesPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editService)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newService)
                .addContainerGap())
        );
        servicesPanelLayout.setVerticalGroup(
            servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, servicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(servicesPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(servicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newService)
                    .add(editService))
                .addContainerGap())
        );

        viewPane.addTab("Services", servicesPanel);

        newScholarship.setText("Create New");
        newScholarship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newScholarshipMouseClicked(evt);
            }
        });

        editScholarship.setText("Update Selected");
        editScholarship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editScholarshipMouseClicked(evt);
            }
        });

        scholarshipsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Citation", "Tease", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scholarshipsTable.getTableHeader().setReorderingAllowed(false);
        scholarshipsPane.setViewportView(scholarshipsTable);
        scholarshipsTable.getColumnModel().getColumn(0).setResizable(false);
        scholarshipsTable.getColumnModel().getColumn(1).setResizable(false);
        scholarshipsTable.getColumnModel().getColumn(2).setResizable(false);
        scholarshipsTable.getColumnModel().getColumn(3).setResizable(false);
        scholarshipsTable.getColumnModel().getColumn(5).setResizable(false);

        org.jdesktop.layout.GroupLayout scholarshipPanelLayout = new org.jdesktop.layout.GroupLayout(scholarshipPanel);
        scholarshipPanel.setLayout(scholarshipPanelLayout);
        scholarshipPanelLayout.setHorizontalGroup(
            scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scholarshipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scholarshipsPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scholarshipPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(editScholarship)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newScholarship)
                .addContainerGap())
        );
        scholarshipPanelLayout.setVerticalGroup(
            scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scholarshipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scholarshipsPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(scholarshipPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newScholarship)
                    .add(editScholarship))
                .addContainerGap())
        );

        viewPane.addTab("Scholarship", scholarshipPanel);

        newPublication.setText("Create New");
        newPublication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPublicationMouseClicked(evt);
            }
        });

        updatePublication.setText("Update Selected");
        updatePublication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePublicationMouseClicked(evt);
            }
        });

        publicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Course Number", "Course Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        publicationsTable.getTableHeader().setReorderingAllowed(false);
        publicationsPane.setViewportView(publicationsTable);
        publicationsTable.getColumnModel().getColumn(0).setResizable(false);
        publicationsTable.getColumnModel().getColumn(1).setResizable(false);
        publicationsTable.getColumnModel().getColumn(2).setResizable(false);
        publicationsTable.getColumnModel().getColumn(3).setResizable(false);
        publicationsTable.getColumnModel().getColumn(4).setResizable(false);

        org.jdesktop.layout.GroupLayout publicationsPanelLayout = new org.jdesktop.layout.GroupLayout(publicationsPanel);
        publicationsPanel.setLayout(publicationsPanelLayout);
        publicationsPanelLayout.setHorizontalGroup(
            publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(publicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(publicationsPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, publicationsPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(updatePublication)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newPublication)
                .addContainerGap())
        );
        publicationsPanelLayout.setVerticalGroup(
            publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, publicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(publicationsPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(publicationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newPublication)
                    .add(updatePublication))
                .addContainerGap())
        );

        viewPane.addTab("Publications", publicationsPanel);

        newKudo.setText("Create New");
        newKudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newKudoMouseClicked(evt);
            }
        });

        updateKudo.setText("Update Selected");
        updateKudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateKudoMouseClicked(evt);
            }
        });

        kudosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Faculty", "Year", "Kudo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        kudosTable.getTableHeader().setReorderingAllowed(false);
        kudosPane.setViewportView(kudosTable);
        kudosTable.getColumnModel().getColumn(0).setResizable(false);
        kudosTable.getColumnModel().getColumn(1).setResizable(false);
        kudosTable.getColumnModel().getColumn(2).setResizable(false);

        org.jdesktop.layout.GroupLayout kudosPanelLayout = new org.jdesktop.layout.GroupLayout(kudosPanel);
        kudosPanel.setLayout(kudosPanelLayout);
        kudosPanelLayout.setHorizontalGroup(
            kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(kudosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(kudosPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kudosPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(updateKudo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newKudo)
                .addContainerGap())
        );
        kudosPanelLayout.setVerticalGroup(
            kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kudosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(kudosPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(kudosPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newKudo)
                    .add(updateKudo))
                .addContainerGap())
        );

        viewPane.addTab("Kudos", kudosPanel);

        usersPanel.setEnabled(false);

        newUser.setText("Create New");
        newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserMouseClicked(evt);
            }
        });

        UpdateUser.setText("Update Selected");
        UpdateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateUserMouseClicked(evt);
            }
        });
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "E-Mail", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usersTable.getTableHeader().setReorderingAllowed(false);
        usersPane.setViewportView(usersTable);
        usersTable.getColumnModel().getColumn(0).setResizable(false);
        usersTable.getColumnModel().getColumn(1).setResizable(false);
        usersTable.getColumnModel().getColumn(2).setResizable(false);
        usersTable.getColumnModel().getColumn(3).setResizable(false);

        org.jdesktop.layout.GroupLayout usersPanelLayout = new org.jdesktop.layout.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(usersPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, usersPanelLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(UpdateUser)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(newUser)
                .addContainerGap())
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(usersPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(usersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newUser)
                    .add(UpdateUser))
                .addContainerGap())
        );

        viewPane.addTab("Users", usersPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewPane)
        );

        viewPane.getAccessibleContext().setAccessibleName("User");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        //System.out.println("test");
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCourseMouseClicked
        n = new CourseWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newCourseMouseClicked

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateUserActionPerformed

    // Editing a Course
    private void editCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCoursesMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new CourseWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_editCoursesMouseClicked

    //New Service
    private void newServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newServiceMouseClicked
        n = new ServiceWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newServiceMouseClicked

    private void editServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editServiceMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new ServiceWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_editServiceMouseClicked

    private void newScholarshipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newScholarshipMouseClicked
        n = new ScholarshipWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newScholarshipMouseClicked

    private void editScholarshipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editScholarshipMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new ScholarshipWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_editScholarshipMouseClicked

    private void newPublicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPublicationMouseClicked
        n = new PublicationWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newPublicationMouseClicked

    private void updatePublicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePublicationMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new PublicationWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_updatePublicationMouseClicked

    private void newKudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newKudoMouseClicked
        n = new KudoWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newKudoMouseClicked

    private void updateKudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateKudoMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new KudoWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_updateKudoMouseClicked

    private void newUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseClicked
        n = new UserWindow(this);
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_newUserMouseClicked

    private void UpdateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateUserMouseClicked
        //This would normally pull data from the table on the page, but this
        //functionality is pending
        n = new UserWindow(this, "777");
        n.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_UpdateUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoursesPanel;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JScrollPane coursesPane;
    private javax.swing.JTable coursesTable;
    private javax.swing.JButton editCourses;
    private javax.swing.JButton editScholarship;
    private javax.swing.JButton editService;
    private javax.swing.JScrollPane kudosPane;
    private javax.swing.JPanel kudosPanel;
    private javax.swing.JTable kudosTable;
    private javax.swing.JScrollPane loginPane;
    private javax.swing.JTextArea loginText;
    private java.awt.Button logoutButton;
    private javax.swing.JButton newCourse;
    private javax.swing.JButton newKudo;
    private javax.swing.JButton newPublication;
    private javax.swing.JButton newScholarship;
    private javax.swing.JButton newService;
    private javax.swing.JButton newUser;
    private javax.swing.JScrollPane publicationsPane;
    private javax.swing.JPanel publicationsPanel;
    private javax.swing.JTable publicationsTable;
    private javax.swing.JPanel scholarshipPanel;
    private javax.swing.JScrollPane scholarshipsPane;
    private javax.swing.JTable scholarshipsTable;
    private javax.swing.JScrollPane servicesPane;
    private javax.swing.JPanel servicesPanel;
    private javax.swing.JTable servicesTable;
    private javax.swing.JButton updateKudo;
    private javax.swing.JButton updatePublication;
    private javax.swing.JScrollPane usersPane;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTable usersTable;
    private javax.swing.JTabbedPane viewPane;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
